receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true
  azuremonitor:
    connection_string: "InstrumentationKey=de8931f3-ad4c-4a0d-8817-f2cfd6cd1746;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, azuremonitor]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, loki, azuremonitor]